version: 2
updates:
- package-ecosystem: npm
  directory: /
  schedule:
    interval: weekly
    day: tuesday
    time: "03:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  reviewers:
  - "ChristophWurst"
  - "st3iny"
  commit-message:
    prefix: "chore"
    include: "scope"
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: tuesday
    time: "03:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  reviewers:
  - "ChristophWurst"
  - "st3iny"
  commit-message:
    prefix: ci
    include: scope
