name: Release
on: workflow_dispatch

jobs:
  npm-registry:
    name: 'Npm registry'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: npm registry
    steps:
      - name: Conventional nextcloud npm release
        uses: ChristophWurst/conventional-nextcloud-npm-release@v0.1
        with:
          github-token: ${{ secrets.RELEASE_PAT }}
          npm-token: ${{ secrets.NPM_TOKEN }}
